// This file is autogenerated by server/main.js
export default client => ({
  hello: {
    msg (options = {}) {
      return client.get('/api/hello', options)
    },
    msgWithInjection (options = {}) {
      return client.get('/api/hello-with-injection', options)
    },
  },
})